import {vec3,add,scale,length,sub} from '../core/world/vector3.js';
const clone=structuredClone,round=n=>Math.round(n*1e12)/1e12;
const rv=v=>vec3(round(v.x),round(v.y),round(v.z));
const bin=n=>String(round(n));
export class SensorimotorKernel{
 constructor(embodiment){this.embodiment=embodiment;this.world=embodiment.world;this.models=new Map();this.trials=[];this.nextTrial=1;}
 sample(embodimentId){const readings=this.embodiment.readSensors(embodimentId),present=readings.filter(x=>!x.missing),massTotal=present.reduce((s,x)=>s+this.world.bodies.get(this.embodiment.embodiments.get(embodimentId).bodyIds[x.partId]).mass,0);let center=vec3(),meanVelocity=vec3();for(const x of present){const body=this.world.bodies.get(this.embodiment.embodiments.get(embodimentId).bodyIds[x.partId]);center=add(center,scale(x.position,body.mass));meanVelocity=add(meanVelocity,scale(x.velocity,body.mass));}if(massTotal){center=scale(center,1/massTotal);meanVelocity=scale(meanVelocity,1/massTotal);}const contacts=this.#contacts(embodimentId);return {tick:this.world.tick,centerOfMass:rv(center),meanVelocity:rv(meanVelocity),speed:round(length(meanVelocity)),contactCount:contacts.length,contacts,parts:readings};}
 runTrial({embodimentId,actuatorId,command,steps=1},causeIds=[]){if(!Number.isInteger(steps)||steps<1)throw new Error('Trial steps must be a positive integer');const before=this.sample(embodimentId);const start=this.world.emit('sensorimotor.trial-started',{trialId:`trial-${this.nextTrial}`,embodimentId,actuatorId,command,steps},causeIds);const commanded=this.embodiment.commandActuator(embodimentId,actuatorId,command,[start.id]);this.embodiment.step(steps);const cleared=this.embodiment.clearCommands(embodimentId,[commanded.id]);const after=this.sample(embodimentId),consequence=this.#consequence(before,after),trial={id:`trial-${this.nextTrial++}`,embodimentId,actuatorId,command,steps,beforeTick:before.tick,afterTick:after.tick,consequence};this.trials.push(trial);this.#learn(trial);this.world.emit('sensorimotor.consequence-recorded',{trial:clone(trial),model:this.getModel(actuatorId,command)},[cleared.id]);return clone(trial);}
 #consequence(before,after){const parts={};for(const b of before.parts){const a=after.parts.find(x=>x.partId===b.partId);if(!a||a.missing||b.missing)continue;parts[b.partId]={positionDelta:rv(sub(a.position,b.position)),velocityDelta:rv(sub(a.velocity,b.velocity)),integrityDelta:round(a.integrity-b.integrity)};}return {centerOfMassDelta:rv(sub(after.centerOfMass,before.centerOfMass)),meanVelocityDelta:rv(sub(after.meanVelocity,before.meanVelocity)),speedDelta:round(after.speed-before.speed),contactDelta:after.contactCount-before.contactCount,parts};}
 #learn(trial){const key=`${trial.actuatorId}|${bin(trial.command)}`,old=this.models.get(key)??{actuatorId:trial.actuatorId,command:round(trial.command),samples:0,meanCenterOfMassDelta:vec3(),meanVelocityDelta:vec3(),meanSpeedDelta:0,meanContactDelta:0};const n=old.samples+1,blend=(a,b)=>round(a+(b-a)/n);old.meanCenterOfMassDelta=rv({x:blend(old.meanCenterOfMassDelta.x,trial.consequence.centerOfMassDelta.x),y:blend(old.meanCenterOfMassDelta.y,trial.consequence.centerOfMassDelta.y),z:blend(old.meanCenterOfMassDelta.z,trial.consequence.centerOfMassDelta.z)});old.meanVelocityDelta=rv({x:blend(old.meanVelocityDelta.x,trial.consequence.meanVelocityDelta.x),y:blend(old.meanVelocityDelta.y,trial.consequence.meanVelocityDelta.y),z:blend(old.meanVelocityDelta.z,trial.consequence.meanVelocityDelta.z)});old.meanSpeedDelta=blend(old.meanSpeedDelta,trial.consequence.speedDelta);old.meanContactDelta=blend(old.meanContactDelta,trial.consequence.contactDelta);old.samples=n;this.models.set(key,old);}
 getModel(actuatorId,command){const m=this.models.get(`${actuatorId}|${bin(command)}`);return m?clone(m):null;}
 #contacts(embodimentId){const e=this.embodiment.embodiments.get(embodimentId);if(!e)throw new Error(`Unknown embodiment: ${embodimentId}`);const ids=new Set(Object.values(e.bodyIds));return this.world.observatory.records.filter(x=>x.tick===this.world.tick&&x.type==='collision.resolved'&&(ids.has(x.payload.a)||ids.has(x.payload.b))).map(x=>({a:x.payload.a,b:x.payload.b}));}
 snapshot(){return {nextTrial:this.nextTrial,trials:clone(this.trials),models:[...this.models.entries()].sort(([a],[b])=>a.localeCompare(b)).map(([key,value])=>[key,clone(value)])};}
 static restore(embodiment,snapshot){const k=new SensorimotorKernel(embodiment);k.nextTrial=snapshot.nextTrial;k.trials=clone(snapshot.trials);k.models=new Map(snapshot.models.map(([key,value])=>[key,clone(value)]));return k;}
}
