import {add,sub,scale,length,normalize,vec3} from '../core/world/vector3.js';
import {HUMANOID_BLUEPRINT} from './humanoid-blueprint.js';
const clone=structuredClone,round=n=>Math.round(n*1e12)/1e12;
export class EmbodimentKernel{
 constructor(world,{blueprint=HUMANOID_BLUEPRINT}={}){this.world=world;this.blueprint=blueprint;this.embodiments=new Map();this.nextEmbodiment=1;}
 create({id,origin=vec3(),materialId='rigid-standard'}={},causeIds=[]){id??=`embodiment-${this.nextEmbodiment++}`;if(this.embodiments.has(id))throw new Error(`Duplicate embodiment: ${id}`);const bodyIds={},joints=[];for(const p of this.blueprint.parts){const bodyId=`${id}:${p.id}`,position=add(origin,p.offset);this.world.createBody({id:bodyId,materialId,mass:p.mass,radius:p.radius,position},causeIds);bodyIds[p.id]=bodyId;if(p.parent){const parent=this.blueprint.parts.find(x=>x.id===p.parent);joints.push({id:`${id}:joint:${p.parent}:${p.id}`,parent:p.parent,child:p.id,restLength:round(length(sub(p.offset,parent.offset))),command:0,...this.blueprint.jointDefaults});}}
  const e={id,blueprintId:this.blueprint.id,bodyIds,joints,actuators:joints.map(j=>({id:`actuator:${j.id}`,jointId:j.id,command:0})),sensors:[{id:`sensor:${id}:proprioception`,type:'proprioception'},{id:`sensor:${id}:integrity`,type:'integrity'}]};this.embodiments.set(id,e);this.world.emit('embodiment.created',{embodimentId:id,blueprintId:e.blueprintId,partIds:Object.keys(bodyIds),jointIds:joints.map(j=>j.id),sexCharacteristics:null},causeIds);return id;
 }
 commandActuator(embodimentId,actuatorId,command,causeIds=[]){const e=this.#get(embodimentId),a=e.actuators.find(x=>x.id===actuatorId);if(!a)throw new Error(`Unknown actuator: ${actuatorId}`);if(!Number.isFinite(command)||command < -1||command > 1)throw new Error('Actuator command must be within [-1, 1]');a.command=command;e.joints.find(j=>j.id===a.jointId).command=command;return this.world.emit('actuator.commanded',{embodimentId,actuatorId,command},causeIds);}
 clearCommands(embodimentId,causeIds=[]){const e=this.#get(embodimentId);for(const a of e.actuators)a.command=0;for(const j of e.joints)j.command=0;return this.world.emit('actuator.commands-cleared',{embodimentId},causeIds);}
 step(count=1){for(let n=0;n<count;n++){for(const e of [...this.embodiments.values()].sort((a,b)=>a.id.localeCompare(b.id)))this.#applyJoints(e);this.world.step(1);for(const e of [...this.embodiments.values()].sort((a,b)=>a.id.localeCompare(b.id)))this.#recordSensors(e);}}
 #applyJoints(e){for(const j of [...e.joints].sort((a,b)=>a.id.localeCompare(b.id))){const p=this.world.bodies.get(e.bodyIds[j.parent]),c=this.world.bodies.get(e.bodyIds[j.child]);if(!p||!c)continue;const delta=sub(c.position,p.position),distance=length(delta),normal=distance?normalize(delta):vec3(1,0,0),relative=dotSafe(sub(c.velocity,p.velocity),normal);const extension=distance-j.restLength;const corrective=Math.max(-j.maxForce,Math.min(j.maxForce,-j.stiffness*extension-j.damping*relative));const drive=j.command*j.maxForce,force=scale(normal,round(corrective+drive));const cause=this.world.emit('joint.constraint-evaluated',{embodimentId:e.id,jointId:j.id,distance:round(distance),restLength:j.restLength,command:j.command});this.world.applyForce(p.id,scale(force,-1),[cause.id]);this.world.applyForce(c.id,force,[cause.id]);}}
 #recordSensors(e){const parts=Object.entries(e.bodyIds).map(([partId,bodyId])=>{const b=this.world.bodies.get(bodyId);return b?{partId,position:clone(b.position),velocity:clone(b.velocity),integrity:b.integrity}: {partId,missing:true};});this.world.emit('sensor.sampled',{embodimentId:e.id,samples:parts});}
 readSensors(id){const e=this.#get(id);return Object.entries(e.bodyIds).map(([partId,bodyId])=>{const b=this.world.bodies.get(bodyId);return b?{partId,position:clone(b.position),velocity:clone(b.velocity),integrity:b.integrity}:{partId,missing:true};});}
 snapshot(){return {nextEmbodiment:this.nextEmbodiment,embodiments:[...this.embodiments.values()].sort((a,b)=>a.id.localeCompare(b.id)).map(x=>clone(x))};}
 static restore(world,snapshot,{blueprint=HUMANOID_BLUEPRINT}={}){const k=new EmbodimentKernel(world,{blueprint});k.nextEmbodiment=snapshot.nextEmbodiment;k.embodiments=new Map(snapshot.embodiments.map(e=>[e.id,clone(e)]));for(const e of k.embodiments.values())for(const bodyId of Object.values(e.bodyIds))if(!world.bodies.has(bodyId))throw new Error(`Missing embodiment part: ${bodyId}`);return k;}
 #get(id){const e=this.embodiments.get(id);if(!e)throw new Error(`Unknown embodiment: ${id}`);return e;}
}
const dotSafe=(a,b)=>a.x*b.x+a.y*b.y+a.z*b.z;
