const clone=structuredClone;
const ID=/^(arithmetic|reasoning|language|analysis)\.[a-z0-9-]+$/;
export class CapabilityKernel{
  constructor({emit=()=>({id:null}),requiredPassedTests=2}={}){if(!Number.isInteger(requiredPassedTests)||requiredPassedTests<1)throw new Error('Ongeldige proefdrempel');this.emit=emit;this.requiredPassedTests=requiredPassedTests;this.capabilities=new Map();}
  propose({id,label=id},tick=0,causeIds=[]){if(!ID.test(id)||typeof label!=='string'||!label.trim())throw new Error('Ongeldige cognitieve capability');if(this.capabilities.has(id))return this.get(id);const item={id,label:label.trim(),status:'candidate',origin:'unknown-origin',createdTick:tick,evidence:[],evaluations:[]};this.capabilities.set(id,item);this.emit('capability.proposed',{id,label:item.label,origin:item.origin,tick},causeIds);return clone(item);}
  addEvidence(id,{sourceType,sourceId,summary},tick=0,causeIds=[]){const item=this.#require(id);if(!['human-instruction','perception','memory','self-derived'].includes(sourceType)||typeof sourceId!=='string'||!sourceId||typeof summary!=='string'||!summary.trim())throw new Error('Ongeldige leerevidence');if(item.evidence.some(x=>x.sourceType===sourceType&&x.sourceId===sourceId))throw new Error('Dubbele leerevidence');item.evidence.push({sourceType,sourceId,summary:summary.trim().slice(0,500),tick});this.emit('capability.evidence-recorded',{id,sourceType,sourceId,tick},causeIds);this.#update(item,tick,causeIds);return this.get(id);}
  recordEvaluation(id,{testId,passed,details='',challenge='',expected='',observed='',independent=true,evaluationSource='unknown'},tick=0,causeIds=[]){const item=this.#require(id);if(typeof testId!=='string'||!testId||typeof passed!=='boolean'||typeof details!=='string'||typeof challenge!=='string'||typeof expected!=='string'||typeof observed!=='string'||typeof independent!=='boolean')throw new Error('Ongeldige capabilityproef');if(!['foundation-model','native-runtime','human','unknown'].includes(evaluationSource))throw new Error('Ongeldige proefoorsprong');if(item.evaluations.some(x=>x.testId===testId))throw new Error('Dubbele capabilityproef');const normalized=challenge.trim().toLocaleLowerCase();if(normalized&&item.evaluations.some(x=>x.challenge?.trim().toLocaleLowerCase()===normalized))throw new Error('Deze proefopgave is al gebruikt');const evaluation={testId,passed,details:details.slice(0,500),challenge:challenge.trim().slice(0,500),expected:expected.trim().slice(0,500),observed:observed.trim().slice(0,500),independent,evaluationSource,tick};item.evaluations.push(evaluation);this.emit('capability.evaluated',{id,testId,passed,independent,evaluationSource,tick},causeIds);this.#update(item,tick,causeIds,evaluation);return this.get(id);}
  #update(item,tick,causeIds,latest=null){const qualifying=item.evaluations.filter(x=>x.passed&&x.independent!==false),passed=new Set(qualifying.map(x=>x.testId)).size,wasAvailable=item.status==='available',contested=wasAvailable&&latest?.independent!==false&&latest?.passed===false,next=contested?'contested':item.evidence.length&&passed>=this.requiredPassedTests?'available':'candidate',origin=next==='candidate'?'unknown-origin':item.origin!=='unknown-origin'&&item.origin?item.origin:qualifying.some(x=>x.evaluationSource==='foundation-model')?'foundation-authorized':qualifying.every(x=>x.evaluationSource==='native-runtime')?'aura-learned':'unknown-origin';if(next!==item.status||origin!==(item.origin??'unknown-origin')){item.status=next;item.origin=origin;if(next==='available')item.availableTick=tick;if(next==='candidate')delete item.availableTick;this.emit(`capability.${next}`,{id:item.id,origin,tick,evidenceCount:item.evidence.length,passedTests:passed},causeIds);}}
  #require(id){const item=this.capabilities.get(id);if(!item)throw new Error(`Onbekende capability: ${id}`);return item;}
  get(id){const item=this.capabilities.get(id);return item?clone({...item,origin:item.origin??'unknown-origin'}):null;}
  available(){return [...this.capabilities.values()].filter(x=>x.status==='available').sort((a,b)=>a.id.localeCompare(b.id)).map(x=>({id:x.id,label:x.label,origin:x.origin??'unknown-origin',availableTick:x.availableTick,evidenceCount:x.evidence.length,passedTests:x.evaluations.filter(e=>e.passed&&e.independent!==false).length,sourceTypes:[...new Set(x.evidence.map(e=>e.sourceType))].sort()}));}
  snapshot(){return {requiredPassedTests:this.requiredPassedTests,capabilities:[...this.capabilities.entries()].sort(([a],[b])=>a.localeCompare(b)).map(([id,x])=>[id,clone({...x,origin:x.origin??'unknown-origin'})])};}
  static restore(snapshot,{emit=()=>({id:null})}={}){const k=new CapabilityKernel({emit,requiredPassedTests:snapshot.requiredPassedTests});k.capabilities=new Map(snapshot.capabilities.map(([id,x])=>[id,clone({...x,origin:x.origin??'unknown-origin'})]));return k;}
}
