const clone=structuredClone;const ID=/^(arithmetic|reasoning|language|analysis)\.[a-z0-9-]+$/;
export class CapabilityKernel{
 constructor({emit=()=>({id:null}),requiredPassedTests=2}={}){if(!Number.isInteger(requiredPassedTests)||requiredPassedTests<1)throw new Error('Ongeldige proefdrempel');this.emit=emit;this.requiredPassedTests=requiredPassedTests;this.capabilities=new Map();}
 propose({id,label=id},tick=0,causeIds=[]){if(!ID.test(id)||typeof label!=='string'||!label.trim())throw new Error('Ongeldige cognitieve capability');if(this.capabilities.has(id))return this.get(id);const item={id,label:label.trim(),status:'candidate',createdTick:tick,evidence:[],evaluations:[]};this.capabilities.set(id,item);this.emit('capability.proposed',{id,label:item.label,tick},causeIds);return clone(item);}
 addEvidence(id,{sourceType,sourceId,summary},tick=0,causeIds=[]){const item=this.#require(id);if(!['human-instruction','perception','memory','self-derived'].includes(sourceType)||typeof sourceId!=='string'||!sourceId||typeof summary!=='string'||!summary.trim())throw new Error('Ongeldige leerevidence');if(item.evidence.some(x=>x.sourceType===sourceType&&x.sourceId===sourceId))throw new Error('Dubbele leerevidence');item.evidence.push({sourceType,sourceId,summary:summary.trim().slice(0,500),tick});this.emit('capability.evidence-recorded',{id,sourceType,sourceId,tick},causeIds);this.#update(item,tick,causeIds);return this.get(id);}
 recordEvaluation(id,{testId,passed,details=''},tick=0,causeIds=[]){const item=this.#require(id);if(typeof testId!=='string'||!testId||typeof passed!=='boolean'||typeof details!=='string')throw new Error('Ongeldige capabilityproef');if(item.evaluations.some(x=>x.testId===testId))throw new Error('Dubbele capabilityproef');item.evaluations.push({testId,passed,details:details.slice(0,500),tick});this.emit('capability.evaluated',{id,testId,passed,tick},causeIds);this.#update(item,tick,causeIds);return this.get(id);}
 #update(item,tick,causeIds){const passed=new Set(item.evaluations.filter(x=>x.passed).map(x=>x.testId)).size,next=item.evidence.length>0&&passed>=this.requiredPassedTests?'available':'candidate';if(next!==item.status){item.status=next;item.availableTick=tick;this.emit('capability.available',{id:item.id,tick,evidenceCount:item.evidence.length,passedTests:passed},causeIds);}}
 #require(id){const item=this.capabilities.get(id);if(!item)throw new Error(`Onbekende capability: ${id}`);return item;}
 get(id){const item=this.capabilities.get(id);return item?clone(item):null;}
 available(){return [...this.capabilities.values()].filter(x=>x.status==='available').sort((a,b)=>a.id.localeCompare(b.id)).map(x=>({id:x.id,label:x.label,availableTick:x.availableTick,evidenceCount:x.evidence.length,passedTests:x.evaluations.filter(e=>e.passed).length,sourceTypes:[...new Set(x.evidence.map(e=>e.sourceType))].sort()}));}
 snapshot(){return {requiredPassedTests:this.requiredPassedTests,capabilities:[...this.capabilities.entries()].sort(([a],[b])=>a.localeCompare(b)).map(([id,x])=>[id,clone(x)])};}
 static restore(snapshot,{emit=()=>({id:null})}={}){const k=new CapabilityKernel({emit,requiredPassedTests:snapshot.requiredPassedTests});k.capabilities=new Map(snapshot.capabilities.map(([id,x])=>[id,clone(x)]));return k;}
}
