import {strict as assert} from 'node:assert';
const ids=['status','feedback','log','workflow-help','next-action','capability-status','step','run','trial','observe','remember','recall','believe','propose','evaluate','new-hypothesis','start-learning','run-candidate-test','verify-test','test-pass','test-fail','compile','test-model','live-model','relay-endpoint','relay-model','relay-provider','model-input','capability-id','capability-label','lesson-input','test-id','test-challenge','test-expected','test-observed','test-details','reset'];
const nodes=new Map(ids.map(id=>[id,{textContent:'',onclick:null,oninput:null,disabled:false,title:'',className:'',value:''}])),store=new Map();
nodes.get('relay-provider').value='gemini';nodes.get('capability-id').value='arithmetic.multiply';nodes.get('capability-label').value='vermenigvuldigen';nodes.get('relay-endpoint').value='http://127.0.0.1:8787/v1/aura/respond';
Object.defineProperty(globalThis,'document',{value:{querySelector:s=>nodes.get(s.slice(1))},configurable:true});
Object.defineProperty(globalThis,'localStorage',{value:{getItem:k=>store.get(k)??null,setItem:(k,v)=>store.set(k,v),removeItem:k=>store.delete(k)},configurable:true});
Object.defineProperty(globalThis,'location',{value:{reload(){}},configurable:true});Object.defineProperty(globalThis,'confirm',{value:()=>false,configurable:true});Object.defineProperty(globalThis,'navigator',{value:{},configurable:true});
Object.defineProperty(globalThis,'fetch',{value:async(_url,options)=>{const input=JSON.parse(options.body).input;return {ok:true,json:async()=>({provider:'gemini',model:'test',output_text:input.includes('7 × 8')?'56':'54'})};},configurable:true});
await import(`../../src/app.js?learning=${Date.now()}`);
nodes.get('lesson-input').value='Vermenigvuldigen is herhaald optellen.';await nodes.get('start-learning').onclick();
const verify=async(id,challenge,expected)=>{nodes.get('test-id').value=id;nodes.get('test-challenge').value=challenge;nodes.get('test-expected').value=expected;await nodes.get('run-candidate-test').onclick();assert.equal(nodes.get('test-observed').value,expected);await nodes.get('verify-test').onclick();};
await verify('proef-1','7 × 8','56');assert.match(nodes.get('capability-status').textContent,/1\/2/);
await verify('proef-2','9 × 6','54');assert.match(nodes.get('capability-status').textContent,/available/);
await nodes.get('compile').onclick();const saved=JSON.parse(store.get('aura-attention-v0.9.0'));
assert.ok(saved.modelContext.capabilities.includes('arithmetic.multiply'));assert.equal(saved.modelContext.capabilityProvenance[0].independentTests,2);assert.equal(saved.modelContext.capabilityProvenance[0].origin,'foundation-authorized');assert.match(nodes.get('capability-status').textContent,/FOUNDATION TOEGESTAAN/);
