import {vec3,add,sub,scale,length,normalize,finite,dot} from './vector3.js';
import {MaterialRegistry} from '../materials/material-registry.js';
import {Observatory} from '../../observatory/observatory.js';
import {PRNG} from '../randomness/prng.js';
const clone=structuredClone;
const round=n=>Math.round(n*1e12)/1e12;
const rv=v=>vec3(round(v.x),round(v.y),round(v.z));
export class WorldKernel{
 constructor({fixedDelta=1/60,gravity=vec3(0,-9.81,0),seed=1,materials}={}){if(!(fixedDelta>0))throw new Error('fixedDelta must be positive');this.version='0.2.0';this.tick=0;this.fixedDelta=fixedDelta;this.gravity=clone(gravity);this.bodies=new Map();this.resources=new Map();this.materials=materials??new MaterialRegistry();this.observatory=new Observatory();this.random=new PRNG(seed);this.nextBody=1;this.nextProcess=1;}
 emit(type,payload,causeIds=[]){return this.observatory.append({tick:this.tick,type,payload,causeIds});}
 addResource(type,amount,causeIds=[]){if(!type||!Number.isFinite(amount)||amount<=0)throw new Error('Invalid resource');this.resources.set(type,round((this.resources.get(type)??0)+amount));return this.emit('resource.added',{type,amount},causeIds);}
 consumeResource(type,amount){const have=this.resources.get(type)??0;if(!(amount>0)||have+1e-12<amount)throw new Error(`Insufficient resource: ${type}`);this.resources.set(type,round(have-amount));}
 createBody(spec={},causeIds=[]){const material=this.materials.get(spec.materialId);const id=spec.id??`body-${this.nextBody++}`;if(this.bodies.has(id))throw new Error(`Duplicate body: ${id}`);const body={id,materialId:material.id,mass:Number(spec.mass),radius:Number(spec.radius),position:clone(spec.position??vec3()),velocity:clone(spec.velocity??vec3()),acceleration:vec3(),force:vec3(),integrity:spec.integrity??1,degradation:spec.degradation??0,static:Boolean(spec.static)};if(!(body.mass>0&&body.radius>0)||!finite(body.position)||!finite(body.velocity)||!(body.integrity>=0&&body.integrity<=1))throw new Error('Invalid body');this.bodies.set(id,body);this.emit('body.created',{body:clone(body)},causeIds);return id;}
 applyForce(id,force,causeIds=[]){const b=this.#body(id);if(!finite(force))throw new Error('Invalid force');b.force=add(b.force,force);return this.emit('force.applied',{bodyId:id,force:clone(force)},causeIds);}
 damage(id,amount,source='unspecified',causeIds=[]){const b=this.#body(id);if(!(amount>=0))throw new Error('Invalid damage');const m=this.materials.get(b.materialId);const effective=round(amount/Math.max(m.toughness,1e-12));b.integrity=round(Math.max(0,b.integrity-effective));const e=this.emit('material.damaged',{bodyId:id,source,amount,effective,integrity:b.integrity},causeIds);if(b.integrity===0)this.destroyBody(id,'integrity-depleted',[e.id]);return e;}
 degrade(id,exposure=1,causeIds=[]){const b=this.#body(id),m=this.materials.get(b.materialId),amount=round(m.degradationRate*exposure);b.degradation=round(b.degradation+amount);return this.damage(id,amount,'degradation',causeIds);}
 construct({inputs,body},causeIds=[]){const before=this.totalResource();for(const [type,amount] of Object.entries(inputs))if((this.resources.get(type)??0)+1e-12<amount)throw new Error(`Insufficient resource: ${type}`);for(const [type,amount] of Object.entries(inputs))this.consumeResource(type,amount);const process=this.emit('process.construction',{processId:`process-${this.nextProcess++}`,inputs:clone(inputs)},causeIds);const id=this.createBody(body,[process.id]);const consumed=Object.values(inputs).reduce((a,b)=>a+b,0);if(round(before-this.totalResource())!==round(consumed))throw new Error('Resource conservation violation');return id;}
 destroyBody(id,reason='process',causeIds=[]){const b=this.#body(id);this.bodies.delete(id);return this.emit('body.destroyed',{bodyId:id,reason,body:clone(b)},causeIds);}
 transformResource({inputType,outputType,amount,efficiency=1},causeIds=[]){if(!(efficiency>=0&&efficiency<=1))throw new Error('Invalid efficiency');this.consumeResource(inputType,amount);const output=round(amount*efficiency);if(output)this.resources.set(outputType,round((this.resources.get(outputType)??0)+output));return this.emit('process.transformed',{processId:`process-${this.nextProcess++}`,inputType,outputType,amount,output,loss:round(amount-output)},causeIds);}
 step(count=1){if(!Number.isInteger(count)||count<0)throw new Error('Invalid step count');for(let n=0;n<count;n++){this.tick++;const causes=[];for(const b of [...this.bodies.values()].sort((a,b)=>a.id.localeCompare(b.id))){if(b.static)continue;b.acceleration=add(this.gravity,scale(b.force,1/b.mass));b.velocity=rv(add(b.velocity,scale(b.acceleration,this.fixedDelta)));b.position=rv(add(b.position,scale(b.velocity,this.fixedDelta)));b.force=vec3();causes.push(this.emit('body.integrated',{bodyId:b.id,position:clone(b.position),velocity:clone(b.velocity),acceleration:clone(b.acceleration)}).id);}this.#collide(causes);this.emit('world.step',{fixedDelta:this.fixedDelta},causes);}}
 #collide(causes){const list=[...this.bodies.values()].sort((a,b)=>a.id.localeCompare(b.id));for(let i=0;i<list.length;i++)for(let j=i+1;j<list.length;j++){const a=list[i],b=list[j],delta=sub(b.position,a.position),dist=length(delta),min=a.radius+b.radius;if(dist>=min)continue;const normal=dist?normalize(delta):vec3(1,0,0),invA=a.static?0:1/a.mass,invB=b.static?0:1/b.mass,rvn=dot(sub(b.velocity,a.velocity),normal);const penetration=min-dist,total=invA+invB;if(total){if(!a.static)a.position=rv(add(a.position,scale(normal,-penetration*invA/total)));if(!b.static)b.position=rv(add(b.position,scale(normal,penetration*invB/total)));if(rvn<0){const e=Math.min(this.materials.get(a.materialId).restitution,this.materials.get(b.materialId).restitution),impulse=-(1+e)*rvn/total;if(!a.static)a.velocity=rv(add(a.velocity,scale(normal,-impulse*invA)));if(!b.static)b.velocity=rv(add(b.velocity,scale(normal,impulse*invB)));}}causes.push(this.emit('collision.resolved',{a:a.id,b:b.id,normal,penetration:round(penetration)}).id);}}
 #body(id){const b=this.bodies.get(id);if(!b)throw new Error(`Unknown body: ${id}`);return b;}
 totalResource(){return round([...this.resources.values()].reduce((a,b)=>a+b,0));}
 worldState(){return {version:this.version,tick:this.tick,fixedDelta:this.fixedDelta,gravity:clone(this.gravity),bodies:[...this.bodies.values()].sort((a,b)=>a.id.localeCompare(b.id)).map(b=>clone(b)),resources:Object.fromEntries([...this.resources.entries()].sort()),materials:this.materials.snapshot(),randomState:this.random.snapshot(),nextBody:this.nextBody,nextProcess:this.nextProcess};}
 snapshot(){return clone({world:this.worldState(),observatory:this.observatory.snapshot()});}
 static restore(snapshot){const s=clone(snapshot),w=new WorldKernel({fixedDelta:s.world.fixedDelta,gravity:s.world.gravity,materials:MaterialRegistry.restore(s.world.materials)});w.version=s.world.version;w.tick=s.world.tick;w.bodies=new Map(s.world.bodies.map(b=>[b.id,b]));w.resources=new Map(Object.entries(s.world.resources));w.random=PRNG.restore(s.world.randomState);w.nextBody=s.world.nextBody;w.nextProcess=s.world.nextProcess;w.observatory=Observatory.restore(s.observatory);if(!w.observatory.verify())throw new Error('Invalid causal log');return w;}
}
