import {strict as assert} from 'node:assert';
const ids=['status','feedback','log','workflow-help','next-action','capability-status','step','run','trial','observe','remember','recall','believe','propose','evaluate','new-hypothesis','start-learning','verify-test','test-pass','test-fail','compile','test-model','live-model','relay-endpoint','relay-model','relay-provider','model-input','capability-id','capability-label','lesson-input','test-id','test-challenge','test-expected','test-observed','test-details','reset'];
const nodes=new Map(ids.map(id=>[id,{textContent:'',onclick:null,oninput:null,disabled:false,title:'',className:'',value:''}])),store=new Map();
nodes.get('relay-provider').value='gemini';nodes.get('capability-id').value='arithmetic.multiply';nodes.get('capability-label').value='vermenigvuldigen';
Object.defineProperty(globalThis,'document',{value:{querySelector:s=>nodes.get(s.slice(1))},configurable:true});
Object.defineProperty(globalThis,'localStorage',{value:{getItem:k=>store.get(k)??null,setItem:(k,v)=>store.set(k,v),removeItem:k=>store.delete(k)},configurable:true});
Object.defineProperty(globalThis,'location',{value:{reload(){}},configurable:true});Object.defineProperty(globalThis,'confirm',{value:()=>false,configurable:true});Object.defineProperty(globalThis,'navigator',{value:{},configurable:true});
await import(`../../src/app.js?learning=${Date.now()}`);
nodes.get('lesson-input').value='Vermenigvuldigen is herhaald optellen.';await nodes.get('start-learning').onclick();
const verify=async(id,challenge,expected,observed)=>{nodes.get('test-id').value=id;nodes.get('test-challenge').value=challenge;nodes.get('test-expected').value=expected;nodes.get('test-observed').value=observed;await nodes.get('verify-test').onclick();};
await verify('proef-1','7 × 8','56','56');assert.match(nodes.get('capability-status').textContent,/1\/2/);
await verify('proef-2','9 × 6','54','54');assert.match(nodes.get('capability-status').textContent,/available/);
await nodes.get('compile').onclick();const saved=JSON.parse(store.get('aura-generalization-lab-v0.8.5'));
assert.ok(saved.modelContext.capabilities.includes('arithmetic.multiply'));assert.equal(saved.modelContext.capabilityProvenance[0].independentTests,2);
