import {strict as assert} from 'node:assert';
const ids=['status','feedback','log','workflow-help','next-action','capability-status','step','run','trial','observe','remember','recall','believe','propose','evaluate','new-hypothesis','start-learning','run-candidate-test','verify-test','test-pass','test-fail','native-status','native-a','native-b','native-output','native-add-example','native-learn','native-test-id','native-test-a','native-test-b','native-expected','native-run','compile','test-model','live-model','relay-endpoint','relay-model','relay-provider','model-input','capability-id','capability-label','lesson-input','test-id','test-challenge','test-expected','test-observed','test-details','reset'];
const nodes=new Map(ids.map(id=>[id,{textContent:'',onclick:null,oninput:null,disabled:false,title:'',className:'',value:''}])),store=new Map();nodes.get('relay-provider').value='gemini';nodes.get('capability-id').value='arithmetic.multiply';nodes.get('capability-label').value='vermenigvuldigen';
Object.defineProperty(globalThis,'document',{value:{querySelector:s=>nodes.get(s.slice(1))},configurable:true});Object.defineProperty(globalThis,'localStorage',{value:{getItem:k=>store.get(k)??null,setItem:(k,v)=>store.set(k,v),removeItem:k=>store.delete(k)},configurable:true});Object.defineProperty(globalThis,'location',{value:{reload(){}},configurable:true});Object.defineProperty(globalThis,'confirm',{value:()=>false,configurable:true});Object.defineProperty(globalThis,'navigator',{value:{},configurable:true});
await import(`../../src/app.js?native=${Date.now()}`);
for(const [a,b,out] of [[2,3,6],[4,5,20],[3,7,21]]){nodes.get('native-a').value=String(a);nodes.get('native-b').value=String(b);nodes.get('native-output').value=String(out);await nodes.get('native-add-example').onclick();}
await nodes.get('native-learn').onclick();assert.match(nodes.get('native-status').textContent,/repeated-addition/);
for(const [id,a,b,expected] of [['native-1',6,8,48],['native-2',9,4,36]]){nodes.get('native-test-id').value=id;nodes.get('native-test-a').value=String(a);nodes.get('native-test-b').value=String(b);nodes.get('native-expected').value=String(expected);await nodes.get('native-run').onclick();}
assert.match(nodes.get('capability-status').textContent,/AURA AANGELEERD/);const saved=JSON.parse(store.get('aura-native-skill-v0.8.7'));assert.equal(saved.modelBridge.requests.length,0);assert.equal(saved.capability.capabilities[0][1].origin,'aura-learned');
