const clone=structuredClone,round=n=>Math.round(n*1e12)/1e12;
const forbidden=new Set(['objectiveWorld','worldState','observatory','materialId','mass','force','acceleration','integrity','static','bodyId']);
function safe(value,path='evidence'){if(Array.isArray(value)){value.forEach((x,i)=>safe(x,`${path}[${i}]`));return;}if(value&&typeof value==='object')for(const [key,v] of Object.entries(value)){if(forbidden.has(key))throw new Error(`Privileged field rejected: ${path}.${key}`);safe(v,`${path}.${key}`);}}
const key=(subject,predicate)=>`${subject}|${predicate}`;
const difference=(a,b)=>typeof a==='number'&&typeof b==='number'?Math.abs(a-b):a&&b&&typeof a==='object'&&typeof b==='object'?Math.sqrt((a.x-b.x)**2+(a.y-b.y)**2+(a.z-b.z)**2):a===b?0:Infinity;
export class BeliefKernel{
 constructor({emit=()=>({id:null}),staleAfter=120,confidenceDecay=.001,conflictTolerance=.25,maxAlternatives=3}={}){if(!Number.isInteger(staleAfter)||staleAfter<1||confidenceDecay<0||conflictTolerance<0||!Number.isInteger(maxAlternatives)||maxAlternatives<1)throw new Error('Invalid belief configuration');this.emit=emit;this.config={staleAfter,confidenceDecay,conflictTolerance,maxAlternatives};this.beliefs=new Map();this.hypotheses=new Map();this.nextBelief=1;this.nextHypothesis=1;this.lastTick=0;}
 ingestPerception(state,causeIds=[]){this.#validatePerception(state);this.advance(state.tick);const changed=[];for(const item of state.items){const confidence=round(1/(1+Math.max(0,item.uncertainty??0)));for(const [predicate,value] of [['presence',true],['distance',item.distance],['relative-position',item.relativePosition],['apparent-radius',item.apparentRadius]])changed.push(this.#addEvidence({subject:item.track,predicate,value,confidence,tick:state.tick,source:{type:'perception',id:state.observationId}}));}this.emit('belief.perception-ingested',{observationId:state.observationId,beliefIds:[...new Set(changed)]},causeIds);return [...new Set(changed)];}
 ingestRecall(results,currentTick=this.lastTick,causeIds=[]){if(!Array.isArray(results))throw new Error('Recall results must be an array');this.advance(currentTick);const changed=[];for(const result of results){if(!result?.content)continue;this.#validatePerception(result.content);for(const item of result.content.items){const confidence=round(Math.min(.75,(result.accessibility??0)/(1+Math.max(0,item.uncertainty??0))));for(const [predicate,value] of [['presence',true],['distance',item.distance],['relative-position',item.relativePosition],['apparent-radius',item.apparentRadius]])changed.push(this.#addEvidence({subject:item.track,predicate,value,confidence,tick:currentTick,source:{type:'memory',id:result.memoryId}}));}}this.emit('belief.memory-ingested',{beliefIds:[...new Set(changed)]},causeIds);return [...new Set(changed)];}
 proposeHypothesis({subject,predicate,expected,tolerance=this.config.conflictTolerance},causeIds=[]){if(!subject||!predicate||tolerance<0)throw new Error('Invalid hypothesis');safe(expected);const h={id:`hypothesis-${this.nextHypothesis++}`,subject,predicate,expected:clone(expected),tolerance,createdTick:this.lastTick,lastEvaluatedTick:null,support:0,contradiction:0,unknown:0,confidence:.5,status:'undetermined',evidence:[]};this.hypotheses.set(h.id,h);this.emit('hypothesis.proposed',{hypothesis:clone(h)},causeIds);return clone(h);}
 evaluate(id,state,causeIds=[]){const h=this.hypotheses.get(id);if(!h)throw new Error(`Unknown hypothesis: ${id}`);this.#validatePerception(state);this.advance(state.tick);const item=state.items.find(x=>x.track===h.subject),value=item?this.#value(item,h.predicate):undefined;let outcome='unknown';if(value===undefined)h.unknown++;else if(difference(value,h.expected)<=h.tolerance){outcome='support';h.support++;}else{outcome='contradiction';h.contradiction++;}h.lastEvaluatedTick=state.tick;h.confidence=round((h.support+1)/(h.support+h.contradiction+2));h.status=h.support&&h.contradiction?'contested':h.support?'supported':h.contradiction?'contradicted':'undetermined';h.evidence.push({observationId:state.observationId,tick:state.tick,outcome,observed:value===undefined?null:clone(value)});this.emit('hypothesis.evaluated',{hypothesisId:id,outcome,confidence:h.confidence,status:h.status},causeIds);return {hypothesisId:id,outcome,confidence:h.confidence,status:h.status};}
 advance(tick,causeIds=[]){if(!Number.isInteger(tick)||tick<this.lastTick)throw new Error('Belief time cannot move backwards');const elapsed=tick-this.lastTick;if(!elapsed)return;for(const belief of this.beliefs.values()){for(const alternative of belief.alternatives)alternative.confidence=round(Math.max(0,alternative.confidence-this.config.confidenceDecay*elapsed));belief.status=tick-belief.lastEvidenceTick>=this.config.staleAfter?'stale':belief.alternatives.length>1?'contested':'current';}this.lastTick=tick;this.emit('belief.aged',{tick,elapsed},causeIds);}
 getBelief(subject,predicate){const b=this.beliefs.get(key(subject,predicate));return b?clone(b):null;}
 #addEvidence(e){const k=key(e.subject,e.predicate);let belief=this.beliefs.get(k);if(!belief){belief={id:`belief-${this.nextBelief++}`,subject:e.subject,predicate:e.predicate,createdTick:e.tick,lastEvidenceTick:e.tick,status:'current',alternatives:[],provenance:[]};this.beliefs.set(k,belief);}let alternative=belief.alternatives.find(a=>difference(a.value,e.value)<=this.config.conflictTolerance);if(!alternative){alternative={value:clone(e.value),confidence:e.confidence,evidenceCount:0,lastEvidenceTick:e.tick};belief.alternatives.push(alternative);}const n=alternative.evidenceCount+1;if(typeof alternative.value==='number'&&typeof e.value==='number')alternative.value=round(alternative.value+(e.value-alternative.value)/n);else if(alternative.value&&e.value&&typeof e.value==='object')alternative.value={x:round(alternative.value.x+(e.value.x-alternative.value.x)/n),y:round(alternative.value.y+(e.value.y-alternative.value.y)/n),z:round(alternative.value.z+(e.value.z-alternative.value.z)/n)};alternative.evidenceCount=n;alternative.confidence=round(Math.min(1,alternative.confidence+(e.confidence-alternative.confidence)/n));alternative.lastEvidenceTick=e.tick;belief.lastEvidenceTick=e.tick;belief.provenance.push(clone(e.source));belief.alternatives.sort((a,b)=>b.confidence-a.confidence||b.evidenceCount-a.evidenceCount);belief.alternatives=belief.alternatives.slice(0,this.config.maxAlternatives);belief.status=belief.alternatives.length>1?'contested':'current';return belief.id;}
 #value(item,predicate){return predicate==='presence'?true:predicate==='distance'?item.distance:predicate==='relative-position'?item.relativePosition:predicate==='apparent-radius'?item.apparentRadius:undefined;}
 #validatePerception(state){safe(state);if(!state||typeof state.observationId!=='string'||!Number.isInteger(state.tick)||!Array.isArray(state.items))throw new Error('Only valid PERCEIVED_STATE may update beliefs');}
 snapshot(){return {config:clone(this.config),nextBelief:this.nextBelief,nextHypothesis:this.nextHypothesis,lastTick:this.lastTick,beliefs:[...this.beliefs.entries()].sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>[k,clone(v)]),hypotheses:[...this.hypotheses.entries()].sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>[k,clone(v)])};}
 static restore(snapshot,{emit=()=>({id:null})}={}){const k=new BeliefKernel({...snapshot.config,emit});k.nextBelief=snapshot.nextBelief;k.nextHypothesis=snapshot.nextHypothesis;k.lastTick=snapshot.lastTick;k.beliefs=new Map(snapshot.beliefs.map(([id,v])=>[id,clone(v)]));k.hypotheses=new Map(snapshot.hypotheses.map(([id,v])=>[id,clone(v)]));for(const belief of k.beliefs.values())safe(belief);return k;}
}
