import {PRNG} from '../core/randomness/prng.js';
import {sub,length,dot,add,scale,vec3} from '../core/world/vector3.js';
const clone=structuredClone,round=(n,p=4)=>Math.round(n*10**p)/10**p;
const noisy=(n,span,rng)=>round(n+(rng.next()*2-1)*span);
export class PerceptionKernel{
 #world;#embodiment;#random;#tracks=new Map();#nextTrack=1;
 constructor(world,embodiment,{range=8,noise=0.01,seed=9001}={}){if(!(range>0)||!(noise>=0))throw new Error('Invalid perception configuration');this.#world=world;this.#embodiment=embodiment;this.range=range;this.noise=noise;this.#random=new PRNG(seed);this.observations=[];this.nextObservation=1;}
 observe({embodimentId,originPart='head'}={},causeIds=[]){const e=this.#embodiment.embodiments.get(embodimentId);if(!e)throw new Error(`Unknown embodiment: ${embodimentId}`);const originBody=this.#world.bodies.get(e.bodyIds[originPart]);if(!originBody)throw new Error(`Unavailable sensor origin: ${originPart}`);const own=new Set(Object.values(e.bodyIds)),candidates=[...this.#world.bodies.values()].filter(b=>!own.has(b.id)).sort((a,b)=>a.id.localeCompare(b.id)),items=[];for(const body of candidates){const delta=sub(body.position,originBody.position),distance=length(delta);if(distance>this.range||this.#occluded(originBody.position,body,candidates))continue;let track=this.#tracks.get(body.id);if(!track){track=`track-${this.#nextTrack++}`;this.#tracks.set(body.id,track);}items.push(Object.freeze({track,relativePosition:Object.freeze(vec3(noisy(delta.x,this.noise,this.#random),noisy(delta.y,this.noise,this.#random),noisy(delta.z,this.noise,this.#random))),distance:noisy(distance,this.noise,this.#random),apparentRadius:round(body.radius/Math.max(distance,1e-9),4),uncertainty:this.noise}));}
  const state=Object.freeze({observationId:`observation-${this.nextObservation++}`,tick:this.#world.tick,originPart,range:this.range,items:Object.freeze(items)});this.observations.push(clone(state));this.#world.emit('perception.observed',{embodimentId,observation:clone(state)},causeIds);return state;}
 #occluded(origin,target,candidates){const direction=sub(target.position,origin),max=length(direction);if(!max)return false;const unit=scale(direction,1/max);for(const other of candidates){if(other.id===target.id)continue;const rel=sub(other.position,origin),projection=dot(rel,unit);if(projection<=0||projection>=max)continue;const closest=add(origin,scale(unit,projection));if(length(sub(other.position,closest))<other.radius)return true;}return false;}
 snapshot(){return {range:this.range,noise:this.noise,randomState:this.#random.snapshot(),tracks:[...this.#tracks.entries()].sort(([a],[b])=>a.localeCompare(b)),nextTrack:this.#nextTrack,nextObservation:this.nextObservation,observations:clone(this.observations)};}
 static restore(world,embodiment,s){const k=new PerceptionKernel(world,embodiment,{range:s.range,noise:s.noise});k.#random=PRNG.restore(s.randomState);k.#tracks=new Map(s.tracks);k.#nextTrack=s.nextTrack;k.nextObservation=s.nextObservation;k.observations=clone(s.observations);return k;}
}
