const clone=structuredClone,round=n=>Math.round(n*1e12)/1e12;
const forbidden=new Set(['objectiveWorld','worldState','observatory','materialId','mass','force','acceleration','integrity','static','bodyId']);
function assertSafe(value,path='memory input'){if(Array.isArray(value)){value.forEach((x,i)=>assertSafe(x,`${path}[${i}]`));return;}if(value&&typeof value==='object')for(const [key,v] of Object.entries(value)){if(forbidden.has(key))throw new Error(`Privileged field rejected: ${path}.${key}`);assertSafe(v,`${path}.${key}`);}}
export class MemoryKernel{
 constructor({emit=()=>({id:null}),traceCapacity=32,memoryCapacity=64,traceDecay=.0125,memoryDecay=.001,forgetThreshold=.05,consolidationAccesses=2}={}){if(!Number.isInteger(traceCapacity)||traceCapacity<1||!Number.isInteger(memoryCapacity)||memoryCapacity<1||traceDecay<0||memoryDecay<0||forgetThreshold<0||forgetThreshold>=1||!Number.isInteger(consolidationAccesses)||consolidationAccesses<1)throw new Error('Invalid memory configuration');this.emit=emit;this.config={traceCapacity,memoryCapacity,traceDecay,memoryDecay,forgetThreshold,consolidationAccesses};this.traces=new Map();this.memories=new Map();this.nextTrace=1;this.nextMemory=1;this.lastTick=0;}
 record(perceivedState,causeIds=[]){assertSafe(perceivedState);if(!perceivedState||typeof perceivedState.observationId!=='string'||!Number.isInteger(perceivedState.tick)||!Array.isArray(perceivedState.items))throw new Error('Only valid PERCEIVED_STATE can become a sensory trace');if(perceivedState.tick<this.lastTick)throw new Error('Memory time cannot move backwards');this.advance(perceivedState.tick);const trace={id:`trace-${this.nextTrace++}`,kind:'sensory-trace',sourceObservationId:perceivedState.observationId,sourceTick:perceivedState.tick,createdTick:perceivedState.tick,lastAccessTick:perceivedState.tick,accessCount:0,strength:1,content:clone(perceivedState)};this.traces.set(trace.id,trace);const event=this.emit('memory.trace-recorded',{trace:clone(trace)},causeIds);this.#limit(this.traces,this.config.traceCapacity,'sensory-capacity',event.id?[event.id]:[]);return clone(trace);}
 retrieve({track=null,limit=3,currentTick=this.lastTick}={},causeIds=[]){if(!Number.isInteger(limit)||limit<1)throw new Error('Invalid retrieval limit');this.advance(currentTick);const candidates=[...this.traces.values(),...this.memories.values()].map(item=>({item,score:this.#score(item,track,currentTick)})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score||a.item.id.localeCompare(b.item.id)).slice(0,limit),results=[];for(const {item,score} of candidates){item.accessCount++;item.lastAccessTick=currentTick;item.strength=round(Math.min(1,item.strength+.04));results.push({memoryId:item.id,kind:item.kind,sourceTick:item.sourceTick,accessibility:round(score),content:clone(item.content)});if(item.kind==='sensory-trace'&&item.accessCount>=this.config.consolidationAccesses)this.#consolidate(item,causeIds);}this.emit('memory.retrieved',{track,results:clone(results)},causeIds);return results;}
 advance(currentTick,causeIds=[]){if(!Number.isInteger(currentTick)||currentTick<this.lastTick)throw new Error('Memory time cannot move backwards');const elapsed=currentTick-this.lastTick;if(!elapsed)return;for(const item of this.traces.values())item.strength=round(Math.max(0,item.strength-this.config.traceDecay*elapsed));for(const item of this.memories.values())item.strength=round(Math.max(0,item.strength-this.config.memoryDecay*elapsed));this.lastTick=currentTick;this.#forgetWeak(causeIds);this.emit('memory.decayed',{tick:currentTick,elapsed},causeIds);}
 weaken(id,amount,causeIds=[]){if(!(amount>=0&&amount<=1))throw new Error('Invalid weakening amount');const item=this.traces.get(id)??this.memories.get(id);if(!item)throw new Error(`Unknown memory item: ${id}`);item.strength=round(Math.max(0,item.strength-amount));this.emit('memory.weakened',{memoryId:id,amount,strength:item.strength},causeIds);this.#forgetWeak(causeIds);}
 #score(item,track,tick){const contains=!track||item.content.items.some(x=>x.track===track);if(!contains)return 0;const age=Math.max(0,tick-item.sourceTick);return round(item.strength/(1+age*.01));}
 #consolidate(trace,causeIds){if([...this.memories.values()].some(x=>x.sourceTraceId===trace.id))return;const memory={id:`memory-${this.nextMemory++}`,kind:'consolidated-memory',sourceTraceId:trace.id,sourceObservationId:trace.sourceObservationId,sourceTick:trace.sourceTick,createdTick:this.lastTick,lastAccessTick:this.lastTick,accessCount:0,strength:round(trace.strength*.8),content:clone(trace.content)};this.memories.set(memory.id,memory);const event=this.emit('memory.consolidated',{traceId:trace.id,memory:clone(memory)},causeIds);this.#limit(this.memories,this.config.memoryCapacity,'memory-capacity',event.id?[event.id]:[]);}
 #forgetWeak(causeIds){for(const collection of [this.traces,this.memories])for(const item of [...collection.values()].sort((a,b)=>a.id.localeCompare(b.id)))if(item.strength<=this.config.forgetThreshold){collection.delete(item.id);this.emit('memory.forgotten',{memoryId:item.id,reason:'strength-threshold'},causeIds);}}
 #limit(collection,capacity,reason,causeIds){while(collection.size>capacity){const victim=[...collection.values()].sort((a,b)=>a.strength-b.strength||a.createdTick-b.createdTick||a.id.localeCompare(b.id))[0];collection.delete(victim.id);this.emit('memory.forgotten',{memoryId:victim.id,reason},causeIds);}}
 snapshot(){return {config:clone(this.config),nextTrace:this.nextTrace,nextMemory:this.nextMemory,lastTick:this.lastTick,traces:[...this.traces.entries()].sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>[k,clone(v)]),memories:[...this.memories.entries()].sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>[k,clone(v)])};}
 static restore(snapshot,{emit=()=>({id:null})}={}){const k=new MemoryKernel({...snapshot.config,emit});k.nextTrace=snapshot.nextTrace;k.nextMemory=snapshot.nextMemory;k.lastTick=snapshot.lastTick;k.traces=new Map(snapshot.traces.map(([id,v])=>[id,clone(v)]));k.memories=new Map(snapshot.memories.map(([id,v])=>[id,clone(v)]));for(const item of [...k.traces.values(),...k.memories.values()])assertSafe(item.content);return k;}
}
